# Generated by Django 2.1.4 on 2018-12-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('message', models.TextField()),
                ('priority', models.PositiveIntegerField(choices=[(10, 'Chat'), (20, 'Email'), (30, 'Text'), (40, 'Call')])),
                ('responded', models.BooleanField(default=False)),
            ],
        ),
    ]
